### PR TITLE
(Towards #2737) update to fparser 0.2.0

### PR DESCRIPTION
**Pull request by arporter**
Update to use fparser 0.2.0.

### CODE REVIEW

**Comment by arporter** [comment]
I've set the integration tests running...

**Comment by arporter** [comment]
LFRic and compilation integration tests were green. NEMOv5 failed for the usual reason. I broke NEMOv4 yesterday :-(
Therefore I declare this ready for review from anyone!

**Review by TeranIvy — CHANGES_REQUESTED** [review]
I installed PSyclone from this branch and ran the full LFRic test suite. All fine except for the known failures we are still resolving.

`setup.py` change looks good and it's PEP8-conformant. However, I am not sure whether you are importing the right revision for fparser 0.2.0. Grepping for "0.1.4" returns
```
.git/modules/external/fparser/packed-refs:58:6d8481c334fc5996a43f7339c181d87b3d0877a2 refs/tags/0.1.4
changelog:462:	59) PR #2490 towards #2447. Update PSyclone to use fparser 0.1.4 release.
external/fparser/README.md:2:  * 31/01/2024 Version 0.1.4 released (resolves issues with WHERE statements and intrinsics).
```
whereas grepping for "0.2.0" returns (even after `git submodule update --init --recursive`)
```
setup.py:164:        install_requires=['pyparsing', 'fparser>=0.2.0', 'configparser',
```

Looking at https://github.com/stfc/fparser/blob/master/README.md, news about releasing fparser 0.2.0 is definitely there, however it is not visible in this submodule. I would suggest making sure you are importing the revision where fparser README is updated as well as this is now a bit confusing.

**Comment by arporter** [comment]
Thanks Iva. I'd just forgotten to update the NEWS bit of the fparser README before I made the release so I updated it on master afterwards (since it is just announcing that the release has been made). I've updated the git submodule so that it points to that commit now.

**Review by TeranIvy — APPROVED** [review]
All well now. The integration tests completed. 

Updated changelog and user guide. Proceeding to merge.

**Pull request merged**
