### PR TITLE
Update CI software dependencies

### PR DESCRIPTION
**Pull request by nmnobre**

### CODE REVIEW

**Comment by arporter** [comment]
The NEMO integration tests failed (run of MO OpenMP for GPU version). Immediately before the binary is launched HDF5 says it is unhappy:
image

**Comment by nmnobre** [comment]
> The NEMO integration tests failed (run of MO OpenMP for GPU version). Immediately before the binary is launched HDF5 says it is unhappy: image

Can you deploy again? I've requested specific versions of HDF5 and netCDF C as well now.

**Comment by nmnobre** [comment]
Hi @sergisiso, I suspect the remaining error is due to hardcoded paths in the fcm file.
Just getting rid of them should be enough.

**Comment by sergisiso** [comment]
Yep, I now updated it to:
```
%NCDF_HOME           ${NETCDF_FORTRAN_ROOT}
%HDF5_HOME           ${HDF5_ROOT}
```
and relaunch CI

**Comment by nmnobre** [comment]
> ```
> %NCDF_HOME           ${NETCDF_FORTRAN_ROOT}
> %HDF5_HOME           ${HDF5_ROOT}
> ```

Sure, we _shouldn't_ need any `-I` or `-L` flags with the Intel compilers, but that's generic enough too. :)
I've had a look at performance, what do you think? Do you want to maybe rerun the tests later?

**Comment by arporter** [comment]
Will the changes made here have broken things for other PRs on Glados - my NEMO integration tests are failing with:

mpiifort -g -qopenmp -o nemo.exe /home/gh_runner/NEMOGCM_V40/cfgs/SPITZ12_openmp_cpu/BLD/obj/nemo.o -L/home/gh_runner/NEMOGCM_V40/cfgs/SPITZ12_openmp_cpu/BLD/lib -l__fcm__nemo -lstdc++ -L/not/defined/lib -L/apps/packages/netcdf_fortran/4.6.1-oneapi/lib -L/apps/packages/hdf5/1.14.3-oneapi/lib -lnetcdff -lnetcdf -lhdf5_hl -lhdf5 -lm
ld: warning: libhdf5_hl.so.200, needed by /apps/packages/netcdf_c/4.9.0-nvidia-hpcsdk/lib/libnetcdf.so, may conflict with libhdf5_hl.so.310
ld: warning: libhdf5.so.200, needed by /apps/packages/netcdf_c/4.9.0-nvidia-hpcsdk/lib/libnetcdf.so, may conflict with libhdf5.so.310
ld: warning: libmpi.so.40, needed by /apps/packages/netcdf_c/4.9.0-nvidia-hpcsdk/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
ld: warning: libnvomp.so, needed by /apps/packages/netcdf_c/4.9.0-nvidia-hpcsdk/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
ld: warning: libnvhpcatm.so, needed by /apps/packages/netcdf_c/4.9.0-nvidia-hpcsdk/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
ld: warning: libnvcpumath.so, needed by /apps/packages/netcdf_c/4.9.0-nvidia-hpcsdk/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
ld: warning: libnvc.so, needed by /apps/packages/netcdf_c/4.9.0-nvidia-hpcsdk/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
/apps/packages/netcdf_c/4.9.0-nvidia-hpcsdk/lib/libnetcdf.so: undefined reference to `ompi_mpi_comm_null'
/apps/packages/netcdf_c/4.9.0-nvidia-hpcsdk/lib/libnetcdf.so: undefined reference to `MPI_Comm_f2c'
/apps/packages/netcdf_c/4.9.0-nvidia-hpcsdk/lib/libnetcdf.so: undefined reference to `ompi_mpi_char'
...

**Comment by nmnobre** [comment]
So, now the fcm has been changed, the local installations will no longer be found, likely breaking this particular test...
In addition, it seems it's trying to use a module designed for the Nvidia HPC SDK, likely due to a previous, spurious load like we discussed on Friday.

**Comment by sergisiso** [comment]
> I've had a look at performance, what do you think? Do you want to maybe rerun the tests later?

I don't think its needed, the CPU performance will not be accurate because Jony's process is using 100% of a core.

**Comment by nmnobre** [comment]
> > I've had a look at performance, what do you think? Do you want to maybe rerun the tests later?
> 
> I don't think its needed, the CPU performance will not be accurate because Jony's process is using 100% of a core.

Indeed. I was trying to imply we could suspend his process for an hour so you could be sure. :)

**Review by sergisiso — APPROVED** [review]
@nmnobre The changes look alright, I will trigger the CI once more after bringing it to master.
I had inconsistent IO timings in GlaDos since Jony started the job, so I will just look for correctness.

**Comment by sergisiso** [comment]
This is ready to merge but I will wait for @TeranIvy #2393 as hers was marked ready first. There aren't any conflicts.

**Pull request merged**
