### PR TITLE
[Frontend] Lowercase routine names + tag return symbol (for #1688)

### PR DESCRIPTION
**Pull request by nmnobre**

### CODE REVIEW

**Comment by rupertford** [comment]
Hi @nmnobre. Is there a particular reason why you plan to lower case the routine names?

**Comment by nmnobre** [comment]
Hi @rupertford,

1) I'd say my major concern is that, in case-insensitive languages such as Fortran, the same entity can be referred to by a myriad of symbols: all the possible lower and uppercase combinations of the letters in its name. If the case encloses no information, it can (and perhaps should, see below) be dropped. If we ever build a frontend for case-sensitive languages, then it's my opinion the symbols should remain untouched.

2) As briefly explained in #1688, without said change, the return value of Fortran functions is being sometimes saved in a different case to the routine name, causing conflicts when transforming to NEMO-specific PSyIR constructs.

I'm open to suggestions 😊

**Comment by rupertford** [comment]
Thanks for the explanation @nmnobre. The reason I asked is that my understanding is that the PSyIR is set up to be case insensitive and it is therefore the responsibility of the back-ends to deal with this if they need to.

**Comment by nmnobre** [comment]
I see. That works as long as I'm not dealing with rogue developers in a case-sensitive language defining things like: 'int rupert;' and 'int RuPERt;' in the same compilation unit 😝 otherwise, mangling is always an option 🤓

**Comment by rupertford** [comment]
Yes I think at some point we would need to mangle, unless we just switched to case-sensitive matching in the PSyIR and lower/upper-cased everything in the front-end as you originally suggested for this problem. If we did the latter, we could even keep an "original name" if we so desired, that any case insensitive back-ends could use to maintain case from input to output.

**Comment by nmnobre** [comment]
Superseded by #1692.

**Pull request closed without merging**
