### PR TITLE
Fix pycodestyle errors (closes #921)

### LINKED ISSUE #921: pycodestyle fixes
There are a few Python files on master which give pycodestyle errors. These should be fixed.

### PR DESCRIPTION
**Pull request by rupertford**
A number of pycodestyle errors have made their way onto master. This PR removes these.

### CODE REVIEW

**Comment by rupertford** [comment]
```
rupert@DLHRT0028:~/proj/PSyclone/src/psyclone$ pycodestyle *.py                                                                
rupert@DLHRT0028:~/proj/PSyclone/src/psyclone$ pycodestyle */*.py                                                              
rupert@DLHRT0028:~/proj/PSyclone/src/psyclone$ pycodestyle */*/*.py                                                            
rupert@DLHRT0028:~/proj/PSyclone/src/psyclone$ pycodestyle */*/*/*.py                                                           
rupert@DLHRT0028:~/proj/PSyclone/src/psyclone$ pycodestyle */*/*/*/*.py                                                         
rupert@DLHRT0028:~/proj/PSyclone/src/psyclone$ pycodestyle */*/*/*/*/*.py                                                       
*/*/*/*/*/*.py:1:1: E902 FileNotFoundError: [Errno 2] No such file or directory: '*/*/*/*/*/*.py'
```

**Comment by arporter** [comment]
I concur although may I humbly suggest `find . -name \*py -exec pycodestyle {} \;` :-)

**Review by arporter — APPROVED** [review]
All changes are good and are purely cosmetic.
Coverage is 100%.

**Comment by arporter** [comment]
I'll proceed to merge this once #915 is on.

**Pull request merged**
