### PR TITLE
(towards #1259) rename TypeSymbol to DataTypeSymbol

### PR DESCRIPTION
**Pull request by arporter**
Purely does the renaming required as part of #1259.

### CODE REVIEW

**Comment by arporter** [comment]
This is purely a renaming but it touches a lot of files so to keep things as simple as possible I've held off adding any new functionality. Ready for review once CI is happy.

**Review by sergisiso — CHANGES_REQUESTED** [review]
@arporter The name change looks fine to me, the only old references I could find are these test names that could also be updated:
```
src/psyclone/tests/psyir/symbols/datatypesymbol_test.py
44:def test_create_typesymbol():
53:def test_create_typesymbol_wrong_datatype():

src/psyclone/tests/psyir/symbols/datatype_test.py
243:def test_arraytype_typesymbol_only():
255:def test_arraytype_typesymbol():
```

Then building the reference guide I got the following warnings, but grepping I couldn't find where these come from, could you check? (I don't discard is just temporal files in my environment)
```
WARNING: autodoc: failed to import module 'typesymbol' from module 'psyclone.psyir.symbols'; the following exception was raised:
No module named 'psyclone.psyir.symbols.typesymbol'
WARNING: autodoc: failed to import class 'typesymbol.TypeSymbol' from module 'psyclone.psyir.symbols'; the following exception was raised:
No module named 'psyclone.psyir.symbols.typesymbol'
```

Unrelated to your modifications but I also get see some pycodestyle v2.6.0 issues, could you have a look at these:
```
pycodestyle src/
src/psyclone/alg_gen.py:45:1: E302 expected 2 blank lines, found 1
src/psyclone/errors.py:41:1: E302 expected 2 blank lines, found 1
src/psyclone/errors.py:68:1: E302 expected 2 blank lines, found 1
src/psyclone/errors.py:78:1: E302 expected 2 blank lines, found 1
src/psyclone/tests/exceptions_test.py:49:1: E302 expected 2 blank lines, found 1
src/psyclone/tests/exceptions_test.py:62:22: E128 continuation line under-indented for visual indent
src/psyclone/tests/psyir/backend/fortran_test.py:363:26: E128 continuation line under-indented for visual indent
src/psyclone/psyir/backend/visitor.py:49:1: E302 expected 2 blank lines, found 1
src/psyclone/psyir/transformations/transformation_error.py:41:1: E302 expected 2 blank lines, found 1
```

**Comment by hiker** [comment]
I was too slow, I wanted to take that. In order not to block this PR I've opened #1289  - I really think the filenames we are ending up with are way too long.

**Comment by arporter** [comment]
Ready for another look once CI is finished.

**Review by sergisiso — APPROVED** [review]
@arporter All requested changes have been done. pycodestyle doesn't report any issue now and the reference guide issues were in my environment. This PR is ready to be merged.

**Pull request merged**
