### PR TITLE
(Closes #2013) Support logical, scalar arguments in psyad test-harness generation

### LINKED ISSUE #2013: [PSyAD] Add support for logical scalar arguments in test harness generation.
`tl_poly1d_vert_adv_kernel_type` has a scalar argument of `logical` type. As it's a scalar it is read only but the test harness still needs to be extended to support this case.

### PR DESCRIPTION
**Pull request by arporter**

### CODE REVIEW

**Comment by arporter** [comment]
I need to add testing and address the pseudo-random initialisation of integer and boolean scalars.

**Comment by arporter** [comment]
I was going to start adding tests and then realised that the `KernCallInvokeArgList` class (which subclasses `ArgOrdering`) is due for reimplementation using the new metadata handling (e.g. see https://github.com/stfc/PSyclone/pull/2048#issuecomment-1448052293). So perhaps I should re-implement the whole class @rupertford?

**Comment by rupertford** [comment]
> I was going to start adding tests and then realised that the `KernCallInvokeArgList` class (which subclasses `ArgOrdering`) is due for reimplementation using the new metadata handling (e.g. see [#2048 (comment)](https://github.com/stfc/PSyclone/pull/2048#issuecomment-1448052293)). So perhaps I should re-implement the whole class @rupertford?

I have started on the re-implementation - captured in issue #2078 - which is waiting on pr #2048 to get onto master.

**Comment by arporter** [comment]
This one is ready for review now. Just a small increment to the adjoint test-harness generation to support kernels with logical, scalar arguments. Although it is adjoint-related, it's probably self-contained enough for @sergisiso or @hiker to review, otherwise it's one for @rupertford.

**Review by rupertford — APPROVED** [review]
The documentation has been updated as requested. Approving.

**Pull request merged**
