### PR TITLE
Update CI software dependencies

### PR DESCRIPTION
**Pull request by nmnobre**

### CODE REVIEW

**Comment by sergisiso** [comment]
Nemo for CPU with Intel compiler failed with: ./nemo: error while loading shared libraries: libhdf5.so.310: cannot open shared object file: No such file or directory

**Comment by sergisiso** [comment]
It now succeeded, slightly slower, but there may have been somebody in the cpu?
https://charts.mongodb.com/charts-project-0-gvldi/embed/charts?id=6644da54-276c-4aa7-8eb7-ef1a23a5f07d&maxDataAge=3600&theme=light&autoRefresh=true

**Comment by nmnobre** [comment]
> It now succeeded, slightly slower, but there may have been somebody in the cpu?

Yeah, me. :P

**Review by sergisiso — APPROVED** [review]
This is an update of the integration test dependencies, I confirm that all of them still pass. This is ready to merge.

**Pull request merged**
