### PR TITLE
matmul2code bug fix (issue #775)

### PR DESCRIPTION
**Pull request by rupertford**

### CODE REVIEW

**Comment by rupertford** [comment]
Simple bug fix and update of tests. Ready for first review.

**Comment by rupertford** [comment]
Taking this back to bring the branch back up to date.

**Comment by rupertford** [comment]
The conflict was only in the changelog. I'll leave it as ready for review seeing as the code has changed.

**Comment by arporter** [comment]
All examples still work (with compilation) and ditto the tests.

**Pull request merged**
