### PR TITLE
(Closes #1775) fixes post_region_code_gen and improves test fixtures.

### LINKED ISSUE #1775: Running psyir/nodes/omp_directives_test.py::test_omp_taskloop_gencode in isolation fails.
If one does:

    pytest psyir/nodes/omp_directives_test.py::test_omp_taskloop_gencode

then the tests fail. However, if pytest is run on the whole `omp_directives_test.py` file then everything is fine.

### PR DESCRIPTION
**Pull request by arporter**

### CODE REVIEW

**Comment by arporter** [comment]
Since I'd touched configuration.py I've tidied it for pylint and that then led me to touch and tidy two associated test files.

**Comment by arporter** [comment]
This is ready for a first look now. It is a small but important change to the test fixtures and a small bug fix. I've also done some tidying for pylint. I would have used a deepcopy for the test fixture but that failed the Python 3.6 CI run so I reverted to a shallow copy.

**Review by hiker — APPROVED** [review]
Nice fix for the config object. While I spent some time thinking about copy vs deepcopy for the config object, de-fact all our potential testing issues come from simple attributes of the config object (not of e.g. the API-specific config).

**Comment by hiker** [comment]
Thanks for all the pylint fixes. I've brought it up to master, updated changelog, and took the liberty to fix two pylint issues that were missed in modified files. The changes are now pylint clean, no need to update UG.
I did notice that there was a change in the #number in the commits - from issue number #1775 to PR number #1776. I think we should try to stick to the issue numbers :)
Will continue to merge once CI is happy.

**Pull request merged**
