### PR TITLE
(closes #2589) Update LFRic integration test

### LINKED ISSUE #2589: Fix LFRic integration tests

### PR DESCRIPTION
**Pull request by sergisiso**

### CODE REVIEW

**Comment by sergisiso** [comment]
@arporter This now passes all integration tests. At the end I have:
- Updated LFRic to use the new split repository and the GlaDos spack packages.
- Not went ahead with NEMO nvhpc 24.3 due to the issues mentioned in #2591
- Add a commands to upload performance results to the database to start populating it. But I suggest still using the github gist for the time being.
- Let psyclone ignore "nemo" section from .cfg files. Even though we updated all the cfg files in our repo, lfric comes with `lfric_core/etc/psyclone.cfg` that has a "nemo" section. And I believe their build system overwrites the PSYCLONE_CONFIG envvar at some point! Unfortunately, they need to fix this on their end first.

**Comment by sergisiso** [comment]
> Let psyclone ignore "nemo" section from .cfg files. Even though we updated all the cfg files in our repo, lfric comes with lfric_core/etc/psyclone.cfg that has a "nemo" section. And I believe their build system overwrites the PSYCLONE_CONFIG envvar at some point! Unfortunately, they need to fix this on their end first.

Ah, I found its PSYCLONE_CONFIG_FILE in their built system instead of the psyclone's PSYCLONE_CONFIG envvar

**Review by arporter — APPROVED** [review]
I thought I'd approved this but apparently not.
All looks fine. As I said before, I think the NEMO timings could possibly be made more reliable but that's a future issue.

**Comment by hiker** [comment]
> * Let psyclone ignore "nemo" section from .cfg files. Even though we updated all the cfg files in our repo, lfric comes with `lfric_core/etc/psyclone.cfg` that has a "nemo" section. And I believe their build system overwrites the PSYCLONE_CONFIG envvar at some point! Unfortunately, they need to fix this on their end first.

I don't think it uses PSYCLONE_CONFIG, the old build system uses the `-c` command line option.

**Comment by hiker** [comment]
> Ah, I found its PSYCLONE_CONFIG_FILE in their build system instead of the psyclone's PSYCLONE_CONFIG envvar

Ah, I saw this too late - ignore my previous comment :)

**Pull request merged**
