### PR TITLE
(Towards 2421) Suggested fix to inline trans

### PR DESCRIPTION
**Pull request by LonelyCat124**

### CODE REVIEW

**Comment by LonelyCat124** [comment]
@arporter This is my proposed fix for the issues I had with inlining, which should enable more general usage for parallel loops.

**Comment by arporter** [comment]
For some reason, github isn't letting me complete my review properly. The fix looks fine. I think it just needs some comments and an explicit (new) test of the bug that is being fixed. I'll trigger the integration tests now. Note that I've merged master into the branch so you'll need to `pull` before you work on it.

**Comment by LonelyCat124** [comment]
@arporter I added a test to explicitly check this and some comments - let me know if you feel they're enough or is there's anything I've missed.

**Comment by LonelyCat124** [comment]
I'm confused as to why this reports a loss in coverage though? Nothing I've changed should touch the `OMPParallelDirective`

**Review by arporter — APPROVED** [review]
Thanks for those changes. All looks good now and integration tests were fine.
Will proceed to merge.

**Pull request merged**
