### PR TITLE
(Towards #2447) adopt fparser 0.1.4

### PR DESCRIPTION
**Pull request by arporter**
Checks prior to making new fparser release.

### CODE REVIEW

**Comment by arporter** [comment]
CI was green. Running integration tests now...

**Comment by arporter** [comment]
Integration tests were all green. @TeranIvy would you mind testing this branch with LFRic (making sure that you get fparser from the submodule and not pypi)?

**Comment by TeranIvy** [comment]
I installed a PSyclone test environment from this branch on Spice as instructed. Due to LFRic source now referring to the LFRic-specific PSyclone configuration file stored in LFRic source, I did not modify the PSyclone configuration file in the branch.

I ran the full LFRic developer test suite on Spice and all is green. I also ran PSyclone tests with compilation – all fine.

@arporter, as I understand this branch does not have to be merged. If this is correct, will there be another PR to update the fparser submodule after the new fparser release?

**Review by TeranIvy — COMMENTED** [review]
I installed a PSyclone test environment from this branch on Spice as instructed. Due to LFRic source now referring to the LFRic-specific PSyclone configuration file stored in LFRic source, I did not modify the PSyclone configuration file in the branch.

I ran the full LFRic developer test suite on Spice and all is green. I also ran PSyclone tests with compilation – all fine.

@arporter, as I understand this branch does not have to be merged. If this is correct, will there be another PR to update the fparser submodule after the new fparser release?

**Comment by TeranIvy** [comment]
> I installed a PSyclone test environment from this branch on Spice as instructed. Due to LFRic source now referring to the LFRic-specific PSyclone configuration file stored in LFRic source, I did not modify the PSyclone configuration file in the branch.
> 
> I ran the full LFRic developer test suite on Spice and all is green. I also ran PSyclone tests with compilation – all fine.
> 
> @arporter, as I understand this branch does not have to be merged. If this is correct, will there be another PR to update the fparser submodule after the new fparser release?

@arporter, I will close this PR without merging when the fparser 0.1.4 is released. I would also appreciate if you could comment on my question above about the fparser submodule update.

**Comment by sergisiso** [comment]
> Due to LFRic source now referring to the LFRic-specific PSyclone configuration file stored in LFRic source, I did not modify the PSyclone configuration file in the branch.

@TeranIvy I hit the same issue today will trying to test LFRic trunk and it took me a long time to realize that it was not loading the config that I was specifying with the PSYCLONE_CONFIG as we say it does in the psyclone documentation.

Could we at least convert LFRic infrastructure/build/psyclone/psyclone.mk line 20 to 
`PSYCLONE_CONFIG_FILE ?= $(ROOT_DIR)/etc/psyclone.cfg`

so that we can point to different configs with:
`PSYCLONE_CONFIG_FILE=$PSYCLONE_CONFIG make SHELL=/bin/bash`

**Comment by TeranIvy** [comment]
> > Due to LFRic source now referring to the LFRic-specific PSyclone configuration file stored in LFRic source, I did not modify the PSyclone configuration file in the branch.
> 
> @TeranIvy I hit the same issue today will trying to test LFRic trunk and it took me a long time to realize that it was not loading the config that I was specifying with the PSYCLONE_CONFIG as we say it does in the psyclone documentation.
> 
> Could we at least convert LFRic infrastructure/build/psyclone/psyclone.mk line 20 to `PSYCLONE_CONFIG_FILE ?= $(ROOT_DIR)/etc/psyclone.cfg`
> 
> so that we can point to different configs with: `PSYCLONE_CONFIG_FILE=$PSYCLONE_CONFIG make SHELL=/bin/bash`

I'm happy to try this out in the LFRic ticket to move to PSyclone 2.5.0 (https://code.metoffice.gov.uk/trac/lfric/ticket/4263) and report back, @sergisiso 😃

**Comment by arporter** [comment]
I'll update this PR to use the released version of fparser now.

**Comment by arporter** [comment]
Ready for another look now :-)

**Comment by TeranIvy** [comment]
Retested with the full LFRic test suite, all fine. @arporter, does this need to be merged to master as is or will you update the branch further?

**Comment by arporter** [comment]
> Retested with the full LFRic test suite, all fine. @arporter, does this need to be merged to master as is or will you update the branch further?

Thanks Iva. Yes, this can be merged to master.

**Review by TeranIvy — APPROVED** [review]
Tests with compilation and integration tests completed successfully. Proceeding to merge.

**Pull request merged**
