### PR TITLE
Fix element_order error (closes #2185)

### LINKED ISSUE #2185: include element_order from an LFRic module in PSyAD test harness
The test harness hard codes element_order to 1. However, it may have a different value and this has caused errors when validating some of the PSyAD-generated LFRic adjoint kernels. The value should instead be included from the appropriate module file `finite_element_config_mod`.

### PR DESCRIPTION
**Pull request by rupertford**
`LFRicAlg` `create_alg_routine()` was hardcoding `element_order` to `1`. This should be `0` for lowest order which is currently what is always used and the incorrect value was causing errors in the PSyAD test harness. To future proof the code generation, `element_order` is now included from `finite_element_config_mod` instead.

### CODE REVIEW

**Comment by rupertford** [comment]
Ready for first review from @arporter

**Review by arporter — CHANGES_REQUESTED** [review]
Looks fine.
All integration tests pass.
Since I can't easily check the updated code for compilation, please could you check with Terry that this change works for him?
Once that's done this can be merged.

**Comment by DrTVockerodtMO** [comment]
I have tested the new adjoint tests generated via this branch and they pass. Thank you @rupertford !

**Comment by rupertford** [comment]
Thanks @DrTVockerodtMO. This PR is ready for its next review from @arporter, assuming CI happiness after bringing the branch up to date with master.

**Review by arporter — APPROVED** [review]
@DrTVockerodtMO has confirmed this works (thanks).
Will proceed to merge.

**Pull request merged**
