### PR TITLE
(Closes #1626) Enhance Markdown link checks

### LINKED ISSUE #1626: MD Link checker uses 'stable' docs rather than 'latest'
Probably it should always use 'latest'? e.g. at the moment it is reporting dead links because what was `psyclone_command` has become `psyclone_kern` but this isn't in a release of PSyclone yet.

### PR DESCRIPTION
**Pull request by nmnobre**

### CODE REVIEW

**Review by arporter — CHANGES_REQUESTED** [review]
This is nice, thanks Nuno. I like the location of the configuration file so could you merge in the one at `PSyclone/mlc_config.json` and then delete the latter? Please could you also update the bit of the Developer Guide that specifies the location of this file.

**Comment by nmnobre** [comment]
Do you want me to merge or just delete the old file? Currently it doesn't seem to be needed, do we think it will in the future?

**Comment by arporter** [comment]
> Do you want me to merge or just delete the old file? Currently it doesn't seem to be needed, do we think it will in the future?

Oh, that's weird. Are you sure it's not needed? If I do a grep then there are lots of references to `https://code.metoffice.gov.uk/trac/lfric` in the LFRic practicals. Since that site is password protected we should get failures if that file is removed?

**Comment by nmnobre** [comment]
> > Do you want me to merge or just delete the old file? Currently it doesn't seem to be needed, do we think it will in the future?
> 
> Oh, that's weird. Are you sure it's not needed? If I do a grep then there are lots of references to `https://code.metoffice.gov.uk/trac/lfric` in the LFRic practicals. Since that site is password protected we should get failures if that file is removed?

> Hehe, mystery solved... There was a typo in the `mlc_config.json` I added, so nothing was being checked 😇

**Review by arporter — APPROVED** [review]
Changes are all good now.
Updated docs build and look fine.
Will bring up-to-date with master and then merge.

**Comment by nmnobre** [comment]
Hang on, sorry, I want to amend this to enable on-demand checks.

**Comment by nmnobre** [comment]
This should be fine. I’ll only know for sure once it’s merged but, according to the internet, it should be 😝

**Review by arporter — APPROVED** [review]
The GitHub API was playing up yesterday so I didn't manage to finish this.
New addition looks fine (although I'm surprised we need it - I thought we could already just manually request a run of the suite).
I'll merge once I've got the test suite to run through.

**Pull request merged**
