### PR TITLE
Update fparser2.py

### PR DESCRIPTION
**Pull request by schreiberx**
Support files which don't contain anything

### CODE REVIEW

**Comment by arporter** [comment]
Thanks for this fix @schreiberx. We require that all new code be covered by a test. Would you like me to take this on or would you like to do it?

**Comment by schreiberx** [comment]
I'd be grateful if you could take this one.

**Comment by arporter** [comment]
OK, will do :-)

**Comment by arporter** [comment]
I've taken @schreiberx 's branch (thank you), added a test and pushed it to this repo. Therefore PR #1725 supersedes this one.

**Pull request closed without merging**
