### PR TITLE
#917 Trigger compilation of PSyData profile wrapper libraries.

### LINKED ISSUE #917: [PSyData] Profiling example does not compile wrapper libraries if required
Other example trigger a build in the libraries included in psyclone (e.g. dl_esm_inf, or psydata wrapper libaries), but this example does not.

### PR DESCRIPTION
**Pull request by hiker**
Fixed #917. Note that there is some overlap with #846 (since it adds another profile wrapper, which can be used stand-alone as well). My suggestion would be to wait merging this till #846 is in, and once this is done, I'll update this PR to support LFRic.

### CODE REVIEW

**Review by arporter — CHANGES_REQUESTED** [review]
Looks good. I tried building for dl_timer (which I have installed in a different location to you) and the Makefile wouldn't pick up the fact that I'd set DL_TIMER_ROOT. I got it to work by removing the `dl_timer:` before the conditional assignment. Would you mind investigating?

**Comment by hiker** [comment]
> Looks good. I tried building for dl_timer (which I have installed in a different location to you) and the Makefile wouldn't pick up the fact that I'd set DL_TIMER_ROOT. I got it to work by removing the `dl_timer:` before the conditional assignment. Would you mind investigating?

OK, it looks like the 'target-specific settings' (whatever they are exactly called, can't remember now) are NOT passed on to a child makefile. I've worked around this issues.

**Comment by hiker** [comment]
Ready, I hope :)

**Review by arporter — APPROVED** [review]
Build problem has been resolved.
Examples all OK, including with compilation.

**Pull request merged**
