### PR TITLE
(Towards #2132) change private repo to be in stfc organisation.

### PR DESCRIPTION
**Pull request by arporter**
A small PR that changes the private repo used to launch heavier compilation testing etc. Previously this was under my personal github account but now it is under the stfc organisation. I've also taken the opportunity to improve things slightly by making the necessary secrets (for ssh) only available in the `deployment` environment.

I've also altered the other action configuration files so that all the other tests *do not* get launched by the mirror repo. (Currently they get duplicated which is very inefficient.)

### CODE REVIEW

**Comment by arporter** [comment]
I've also been slightly naughty and updated the various RTD confg. files to ensure that graphviz gets installed as I noticed we are not getting the inheritance diagrams produced.

**Comment by arporter** [comment]
This is ready for a first look now from @hiker, @rupertford or @sergisiso. It addresses some of the limitations identified in #2132, primarily by changing the private repo that is used for the compilation tests to one that is in the stfc organisation. I'll make a new document on Teams to record the internal details.

**Comment by arporter** [comment]
(Note that, as with the first PR that added compilation testing, the button to launch it will only be updated once this hits master. For testing purposes, you can change the `on` setting to be `push`.)

**Review by sergisiso — CHANGES_REQUESTED** [review]
@arporter It looks good and I can see in the commit history that it triggers the jobs in the new repo successfully. I just have a couple of comments/suggestions:

- Instead of `if: ${{ github.repository == 'stfc/PSyclone' }}` we could use `if: ${{ github.repository != 'stfc/PSyclone-mirror' }` to enable regular tests. Some people fork the repo and work on it until they have a PR ready and they would expect the CI to work.

- I noticed that the compile tests are done with python3.6 (glados default), but this version is not supported/tested by psyclone. We could be in a situation where the compilation test fails because of a difference btw 3.6 and 3.7. One solution it would be to update the run target to do `python3.8 -m venv .runner_venv` which is also available or instead do a `module load python` before the venv (which uses 3.11).

**Comment by arporter** [comment]
Thanks @sergisiso and good spot on the Python version. I've done as you suggested and altered it to load the python/3.11.3 module before running. Also a good spot on the issue of running actions from forks so I've changed to `!= stfc/PSyclone-mirror` as you suggested.

**Comment by arporter** [comment]
Using the Python 3.11.3 module on Glados doesn't seem to work. I get an error related to sqlite when attempting to run the tests. I can run them OK on my laptop with this python version so it must be something about the environment setup on Glados.

**Comment by arporter** [comment]
OK, working with 3.11.3 now. Ready for another look.

**Pull request merged**
