### PR TITLE
(Closes #2109) Update to fparser 0.1.1

### LINKED ISSUE #2109: Move to fparser 0.1.1
fparser 0.1.0 has been released today. We need to move over to using this in GHA and check that LFRic works correctly with it.

### PR DESCRIPTION
**Pull request by arporter**

### CODE REVIEW

**Comment by arporter** [comment]
@TeranIvy, the branch associated with this PR is what you want to test with :-)

**Review by TeranIvy — APPROVED** [review]
All well. 

I built the PSyclone test environment with fparser installed from the updated submodule. The full LFRic test suite on Spice builds and runs successfully.

Direct `fparser2 --std=f2008` as used in LFRic style checker works fine on all LFRic source. 

Updated changelog and user guide for merge to master. CI permitting, this can go on.

**Comment by TeranIvy** [comment]
@arporter, could you please have a look at the failing tests?

**Review by TeranIvy — CHANGES_REQUESTED** [review]
Changing status from "Approved" due to CI test failures.

**Comment by arporter** [comment]
Thanks for testing @TeranIvy. This PR needs the new release of fparser to be made before it can go on. I've looked at the failing example and it seems to be due to a versioning problem with IPython. I'm not sure why we need IPython but I can investigate that in parallel with releasing 0.1.1 of fparser.

**Comment by arporter** [comment]
I seem to have fixed it. Ready for review now.

**Review by TeranIvy — APPROVED** [review]
All well now. Updated the branch with the master and resolved conflicts in `changelog` and `psyclone.pdf` from the previous merge attempt. Also updated them for the merge to master.

I am proceeding with the merge to master.

**Pull request merged**
