### PR TITLE
(Closes #2351) Fix ref2arrayrange allocate bug

### LINKED ISSUE #2351: `Reference2ArrayRangeTrans` introduces erroneous colon notation in `ALLOCATED` intrinsic
Consider the following example.

```fortran
module my_module
  implicit none
  public

  contains
  subroutine my_subroutine()
    integer :: my_dim
    integer, allocatable, dimension(:,:) :: my_array

    my_dim = 10

    if (.NOT.ALLOCATED(my_array)) then
      ALLOCATE(my_array(1:my_dim,1:my_dim))
    end if

  end subroutine my_subroutine

end module my_module
```

If I apply the transformation script

```python
from psyclone.psyir import nodes
from psyclone.psyir.transformations import Reference2ArrayRangeTrans
from psyclone.psyir import symbols
from psyclone.transformations import TransformationError


def trans(psy):
    for invoke in psy.invokes.invoke_list:
        for reference in invoke.schedule.walk(nodes.Reference, stop_type=nodes.Reference):
            if isinstance(reference.symbol, symbols.DataSymbol):
                try:
                    Reference2ArrayRangeTrans().apply(reference)
                except TransformationError:
                    pass
    return psy
```

then I get the output

```fortran
module my_module
  implicit none
  public

  contains
  subroutine my_subroutine()
    integer :: my_dim
    integer, allocatable, dimension(:,:) :: my_array

    my_dim = 10
    if (.NOT.ALLOCATED(my_array(:,:))) then
      ALLOCATE(my_array(1:my_dim,1:my_dim))
    end if

  end subroutine my_subroutine

end module my_module
```

The compiler I'm using (NVHPC) doesn't like the colon notation being used inside the `ALLOCATED` intrinsic call.

### PR DESCRIPTION
**Pull request by arporter**

### CODE REVIEW

**Comment by arporter** [comment]
This is a small fix for #2351 - I've generalised the validate so it now checks the `is_inquiry` property that Sergi recently added for intrinsics. I've fired off the integration tests.
Ready for review from @sergisiso, @rupertford  or @hiker.

**Review by hiker — APPROVED** [review]
Clean simple fix, good improvement. I had a closer look, and noticed that e.g. `lbound(c(:))` is valid (accepted by intel, gnu, nvidia), but even the compilers could not agree on the meaning if e.g. `c` is unallocated, and I could not see any good reason to use this. So I'll progress to merge as soon as CI is happy.

**Comment by hiker** [comment]
OK, I need to take that back, I just realised that while all lines are actually covered by tests, the `intrinsic_call_test` files does not cover all lines, including code added here:
```
pytest --cov-report term-missing --cov psyclone.psyir.nodes.intrinsic_call  /home/joerg/work/psyclone/src/psyclone/tests/psyir/nodes/intrinsic_call_test.py
/home/joerg/.local/lib/python3.10/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.10.12, pytest-7.2.2, pluggy-1.0.0
rootdir: /home/joerg/work/psyclone, configfile: setup.cfg
plugins: pylint-0.19.0, pep8-1.0.6, flakes-4.0.5, xdist-3.2.1, anyio-3.6.2, cov-4.0.0
collected 30 items                                                                                                                                                                 

psyir/nodes/intrinsic_call_test.py ..............................                                                                                                            [100%]

---------- coverage: platform linux, python 3.10.12-final-0 ----------
Name                                                                   Stmts   Miss  Cover   Missing
----------------------------------------------------------------------------------------------------
/home/joerg/work/psyclone/src/psyclone/psyir/nodes/intrinsic_call.py     280      2    99%   742, 964
----------------------------------------------------------------------------------------------------
TOTAL                                                                    280      2    99%
```
Line 742 (`hash`) is not your fault, but 964 is :)

Not sure what would happen if  I 'dismissed' my review, so I'll leave it in the approved state, but added 'reviewed with action' label.

**Comment by arporter** [comment]
Thanks for spotting that Joerg. I've added two new tests to get 100% coverage. Ready for another look assuming CI happiness...

**Review by hiker — APPROVED** [review]
Thanks a lot!

**Pull request merged**
