### PR TITLE
Example code should use a function (towards #1618)

### PR DESCRIPTION
**Pull request by rupertford**
The example code `examples/lfric/code/gw_mixed_schur_preconditioner_alg_mod.x90` is not valid as if you have an interface with the same name as a type then the associated routines must be functions and in the example the routine is a subroutine. For example, the following is invalid:

```
module test_mod
  type, public :: test_type
  end type
  interface test_type
     module procedure constructor
  end interface
contains
  subroutine constructor
  end subroutine
end module
```
```
rupert@xxx$ gfortran -c interface.f90
interface.f90:2:27:

    2 |   type, public :: test_type
      |                           1
Error: In generic interface 'test_type' at (1) procedures must be all FUNCTIONs as the generic name is also the name of a derived type
```

and the following is OK:

```
module test_mod
  type, public :: test_type
  end type
  interface test_type
     module procedure constructor
  end interface
contains
  function constructor() result(self)
  end function
end module
```

### CODE REVIEW

**Comment by rupertford** [comment]
Ready for review. This is a very small change in example code. Probably best suited for @arporter or @TeranIvy

**Comment by TeranIvy** [comment]
@rupertford, happy to take it if you're OK with me doing the built-ins PR first. How did you encounter the bug? When I run `make compile` with `gfortran` 6.1.0 in `examples/lfric` everything works fine!

**Comment by rupertford** [comment]
> @rupertford, happy to take it if you're OK with me doing your built-ins PR first. How did you encounter the bug? When I run `make compile` with `gfortran` 6.1.0 in `examples/lfric` everything works fine!

Thanks @TeranIvy. Yes I'm happy for this to be done after the built-ins PR. `make compile` does not compile this code, presumably because it contains lfric infrastructure calls, which is why we don't see any errors. The code is used in egs 12, 13 and 15 I think. I encountered it through a circuitous route and it does not actually affect anything in PSyclone but it is better to have more correct code even if it is not compiled. The version of gfortran I used is 9.3.0.

**Review by TeranIvy — COMMENTED** [review]
Can confirm that the GW preconditioner constructor on LFRic trunk is function and not subroutine.

Ran full battery of tests with compilation, LFRic examples with compilation and documentation building.

Updated changelog and user guide. CI permitting, proceeding to merge.

**Pull request merged**
