### PR TITLE
#154 change to use fparser set_format() instead of set_mode()

### PR DESCRIPTION
**Pull request by arporter**
I've also been a good boy and updated the interface doc strings for all the routines I've touched.

### CODE REVIEW

**Comment by arporter** [comment]
On seeing the Travis test failures I realise that we need to make a new fparser release so we have a fixed target to point PSyclone at. (The tests all pass on my local machine where I have the HEAD of master of fparser.)

**Comment by TeranIvy** [comment]
Hi @arporter! I guess making a new fparser release includes merging [fparser PR 78](https://github.com/stfc/fparser/pull/78). Are there any plans to include [fparser PR 71](https://github.com/stfc/fparser/pull/71) as well?

**Comment by TeranIvy** [comment]
Would it be worth adding a "user warning", either to the README file or documentation that the release 1.6.0 will not work with fparser 0.0.6 and older versions?

**Comment by arporter** [comment]
I've updated the dependency information in `setup.py` to specify version >= 0.0.7 of fparser.
I've also updated the necessary sections in the documentation to make clear which version of fparser is required. I've taken the opportunity to bring the documentation up-to-date by making the use of pip more prominent and removing the now incorrect statement that fparser requires numpy.

**Comment by arporter** [comment]
The examples all work OK and all the tests pass (including when compilation is enabled).

**Comment by arporter** [comment]
Please don't review yet - I've just remembered that I think I need to bring the branch up-to-date with master.

**Comment by arporter** [comment]
Branch brought up-to-date - ready for review.

**Pull request merged**
