### PR TITLE
Issue #438. Pytest quick fix

### PR DESCRIPTION
**Pull request by sergisiso**
Limits pytest version in order to work with new pip installations. See #438.

(also, I am wondering if this is related with the codecov issues we are having)

### CODE REVIEW

**Comment by sergisiso** [comment]
@rupertford @arporter At the moment master is broken if used with a clean pip install or update, this should fix it. This issue was not raised by travis because they use a slightly older version of pip 19.0, but it happens with the virtualenv pip 19.1. It should be ready for review when all test pass.

**Comment by sergisiso** [comment]
I manually submitted a codecov report using the codecov cli tool, if this is in master I belive it will report coverage tests again :)

image

**Comment by sergisiso** [comment]
@arporter I added the Warning in the Getting Going, there are other references to pytest which I haven't modified but I think it's better to keep this simple and leave the issue #438 opened until we fix it properly, then we can remove the version limit and the Warning.

**Comment by arporter** [comment]
Thanks for tweaking the documentation and I agree - there's no point going to town on it (i.e. making sure we cover everywhere py.test is mentioned.

**Comment by arporter** [comment]
Oh, and well done for fixing CodeCov! You'll have to explain to me what you did (tomorrow perhaps).

**Pull request merged**
