### PR TITLE
Fix link to GungHo

### PR DESCRIPTION
**Pull request by kinow**
Hi,

I think the link to the paper is broken. MO has a page for GungHo similar to the one for LFRic, so I think this could be a replacement for the PDF article?

Cheers
Bruno

### CODE REVIEW

**Comment by rupertford** [comment]
Thanks Bruno (@kinow), the pdf had more information on the GungHo project than the web page does,, so rather than just accepting your PR, I've asked the LFRic team if they know where the pdf has moved to and also whether they think it would be more robust to just reference the web page you suggest instead.

**Comment by kinow** [comment]
Thanks @rupertford!

**Comment by rupertford** [comment]
Thanks @kinow. I went with your proposed change. Note, I also added your name as a modifier in the relevant file. I was a bit naughty and did this change myself (rather than get you to do it) as it seemed a bit silly to get you to do it and we didn't have the information in the correct format (with copyright info) in any case!

**Comment by kinow** [comment]
All good @rupertford , thanks for taking care of this. I couldn't find a `CONTRIBUTING.md`, but if there are any docs that contributors should read before writing issues/PR's, to give less work to reviewers, just let me know and I will read them before the next PR.

**Comment by rupertford** [comment]
@kinow, that is a good point. I've made issue #484 to add a CONTRIBUTING.md file but in the meantime we have information on our wiki: https://github.com/stfc/PSyclone/wiki which has code review and interface markup guidelines. We also have a developers guide which would hopefully provide some useful information: https://psyclone-dev.readthedocs.io/en/latest/

**Pull request merged**
