### PR TITLE
(closes #2433) process_nemo.py argparse aggregates provided -I flags

### LINKED ISSUE #2433: Performance regression in NEMO OpenMP for GPU
I got GLaDOS empty for the integration test and I noticed the OpenMP GPU is 25% slower than it use to be. The regression seems to be around SaveStatements or something merged around that time:
```
342_kernels_with_calls f298725a3eda1065cbd5b6b84ad8be3d785eb8dc 11.650 11.650
2243_save_stmt 421ec7507e645b6496bbc779a772aa557bbe8094 14.553 14.553
2368_depth_kwarg_walk 9d96edf370f3269d76fd6037705da8153441f20f 11.602 11.602
2243_save_stmt 7bff83077da63f74bf37f1ea9a0f7f39961f75d3 14.535 14.535
```

Curiously, it does not affect the similar OpenACC loops implementation (because it already has the slower performance) 
```
342_kernels_with_calls f298725a3eda1065cbd5b6b84ad8be3d785eb8dc 13.940 13.940
2243_save_stmt 421ec7507e645b6496bbc779a772aa557bbe8094 13.995 13.995
2368_depth_kwarg_walk 9d96edf370f3269d76fd6037705da8153441f20f 13.977 13.977
2243_save_stmt 7bff83077da63f74bf37f1ea9a0f7f39961f75d3 14.050 14.050
```

It would be good to know what is this about.

### PR DESCRIPTION
**Pull request by sergisiso**

### CODE REVIEW

**Comment by sergisiso** [comment]
This is ready to review, probably for @arporter

**Comment by sergisiso** [comment]
@arporter Addressed the comment and launched the integration test. If the tests succeed this is ready for another look.

**Review by arporter — COMMENTED** [review]
Requested change has been made and CI still green.
Just waiting on integration tests now.

**Review by arporter — APPROVED** [review]
All checks were green.
Ready to be merged once CI complete.

**Pull request merged**
