### PR TITLE
(Closes #1488) configure MD link checker to skip links to MO wiki

### LINKED ISSUE #1488: MD link checking is reporting failures
Weirdly, the Markdown link checker has suddenly started reporting errors (relating to URLs that point to the MO's password-protected wiki). How these passed before I don't know.

### PR DESCRIPTION
**Pull request by arporter**

### CODE REVIEW

**Comment by arporter** [comment]
Adding 'mlc_config.json' in the root directory is successful - the link checker reports that it is using this file. Having said that, my other PR where I first saw this failure is now suddenly not failing!

**Comment by arporter** [comment]
Since this only affects the MD link checker I'm going to assume the rest of the CI is happy and mark this for review. One for anyone!

**Comment by TeranIvy** [comment]
Happy to take it!

**Review by TeranIvy — CHANGES_REQUESTED** [review]
All looks well, but unfortunately there are conflicts in the `working_practises.rst` that I'm not quite sure how to fix. I would kindly ask @arporter to merge the master and resolve conflicts and after that we are ready to go.

**Comment by arporter** [comment]
Thanks Iva. I've done the merge and fixed the conflict. Updated documentation builds and looks OK.
Ready for next review.

**Review by TeranIvy — APPROVED** [review]
All well: Tests with compilation pass, examples run, documentation builds (both User and Developer Guide). Coverage is not changed and no `pylint` and `pycodestyle` checks are applicable here.

Fixed a minor typo, refreshed the branch with the current master and updated changelog and User Guide. CI permitting, this can be merged.

**Pull request merged**
