### PR TITLE
 Add data type metadata for fields and operators in remaining Python test modules (completes #817)

### PR DESCRIPTION
**Pull request by TeranIvy**
This PR completes #817. It updates field and operator metadata in the remaining LFRic (Dynamo0.3) Python test modules.

This PR has to be reviewed and merged after #1044 (updates test kernels except for 3 of them left to ensure support for both the old and the new style field and operator metadata), #1045 (updates examples) and #1051 (updates tutorials).

*Notes:*
- I updated the `argument_mod.F90` with the latest version from the LFRic trunk (and slightly modified it to reference relevant PSyclone issues.
- I checked the tests and LFRic tutorials and full examples with compilation. They are all fine.
- `lfric_stencil_tests.py` had some `pycodestyle` and `pylint` errors so I cleaned them up.

Ready for review.

### CODE REVIEW

**Comment by TeranIvy** [comment]
Taking back the branch for a moment to add `DOMAIN` iterator ID.

**Comment by TeranIvy** [comment]
Added the `domain` kernel iterator and updated the branch with the latest master. Ready for review.

**Review by arporter — CHANGES_REQUESTED** [review]
All changes are good and are pylint/pycodestyle clean.
No need to update documentation - no source files are changed.
Examples are OK, including with compilation.
Only problem is that the update to argument_mod.F90 is causing several of the compilation tests to fail (because one or more of the test kernels explicitly import GH_COLUMN_WISE... even though it is never used). Once that's fixed this can be merged.

**Comment by TeranIvy** [comment]
Oops, I forgot to remove the unused CMA metadata (`GH_COLUMN_BANDED_DOFMAP` and `GH_COLUMN_INDIRECTION_DOFMAP`) before sending the branch for review. It is now done (in test CMA kernels and one example CMA kernel) and tested with compilation with Intel. The branch is also updated with the latest master.

**Review by arporter — APPROVED** [review]
Requested change has been made - tests and examples are all now OK with compilation.

**Pull request merged**
