### PR TITLE
(Closes #1923) rm broken reference to KernelTrans in Dev Guide

### LINKED ISSUE #1923: Errors when building Dev Guide.
#1899 merged KernelTrans into KernelModuleInlineTrans but it is still referenced in the Dev. Guide. This needs to be updated.

### PR DESCRIPTION
**Pull request by arporter**
Small change to fix the Developer Guide which was broken by #1899 (and I failed to spot when reviewing).

### CODE REVIEW

**Comment by arporter** [comment]
One for @sergisiso to check that he's happy that what I've done reflects what he did in #1899.

**Review by sergisiso — CHANGES_REQUESTED** [review]
@arporter Ah thanks I also didn't notice the error. Since we are here I just noticed that the reference guide also shows this error:
`Module psyclone.domain.common.transformations doesn't have a element RaiseCall2InvokeTrans`
because:
`../../src/psyclone/domain/common/transformations/__init__.py` misnames the class in the all list
Can you fix this please?

**Comment by arporter** [comment]
Oh yes, good spot. Fixed now. I was also starting to see Doxygen warnings about the number of nodes in some of our graphs so I've increased the limit for that. I've also updated conf.py to specify English as the previous value of `None` was generating a warning.

**Review by sergisiso — APPROVED** [review]
@arporter My comment was addressed. Most Developers guide and Reference Guide warning/errors are gone now. This is ready to merge.

**Pull request merged**
