### PR TITLE
Provide alternative link for GOcean project

### PR DESCRIPTION
**Pull request by BHFock**
Suggestion of an alternative for a broken link to GOcean project in the Introduction of the documentation.

### CODE REVIEW

**Review by arporter — CHANGES_REQUESTED** [review]
Many thanks for this update. Please could you also update the `linkcheck_ignore` setting in `doc/user_guide/introduction.rst` to remove this old link.

**Comment by BHFock** [comment]
[5aae62e](https://github.com/stfc/PSyclone/pull/2123/commits/5aae62e6611a561e83d7a1aba38148b9dcf0e8d4) removes https://puma.nerc.ac.uk/trac/GOcean  from linkcheck_ignore. However, there is another reference to  https://puma.nerc.ac.uk/trac/GOcean in [doc/user_guide/gocean1p0.rst](
https://github.com/BHFock/PSyclone/blob/documentation/doc/user_guide/gocean1p0.rst#the-gocean-library) which I don't know how to handle.

**Comment by arporter** [comment]
> [5aae62e](https://github.com/stfc/PSyclone/pull/2123/commits/5aae62e6611a561e83d7a1aba38148b9dcf0e8d4) removes https://puma.nerc.ac.uk/trac/GOcean from linkcheck_ignore. However, there is another reference to https://puma.nerc.ac.uk/trac/GOcean in [doc/user_guide/gocean1p0.rst](https://github.com/BHFock/PSyclone/blob/documentation/doc/user_guide/gocean1p0.rst#the-gocean-library) which I don't know how to handle.

Ah! That is very out of date - thanks for pointing this out. For now I'll revert my suggested change to the link-check configuration and open a new issue to update this document.

**Comment by arporter** [comment]
Link check failure is Binder again. Otherwise this is fine.

**Pull request merged**
